# Assignment 3

# Q1).

In [1]:
import numpy as np
print(np.arange(2, 50, 3) )

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q2).

In [1]:
import numpy as np
First_list = int(input("Enter the size of list : "))
print("\n")
numList_1 = list(int(num) for num in input("Enter the list numbers separated by space > ").strip().split())[:First_list]
print("First List : ",numList_1)
print("\n")

Second_list = int(input("Enter the size of list : "))
print("\n")
numList_2 = list(int(num) for num in input("Enter the list numbers separated by space > ").strip().split())[:Second_list]
print("Second List: ",numList_2)
print("\n")

Array_1 = np.array(numList_1)
Array_2 = np.array(numList_2)

print("Array1 as Numpy_Array > ",Array_1)
print("Array2 as Numpy_Array > ",Array_2)
print("\n")

concatenated_array = np.concatenate((Array_1, Array_2), axis=0)
print("Concatenated Array > ", concatenated_array)
print("\n")
concatenated_array.sort()
print("Sorted Array > ", concatenated_array)

Enter the size of list : 5


Enter the list numbers separated by space > 52 41 5 69 95
First List :  [52, 41, 5, 69, 95]


Enter the size of list : 5


Enter the list numbers separated by space > 112 47 6 32 95
Second List:  [112, 47, 6, 32, 95]


Array1 as Numpy_Array >  [52 41  5 69 95]
Array2 as Numpy_Array >  [112  47   6  32  95]


Concatenated Array >  [ 52  41   5  69  95 112  47   6  32  95]


Sorted Array >  [  5   6  32  41  47  52  69  95  95 112]


# Q3).

In [4]:
import numpy as np
arr2D = np.array([[11,12,13,11], [21,22,23,24], [31,32,33,34]])
print("2D Numpy Array")
print(arr2D)
print("\n")
NumOfRows = np.size(arr2D,0)
NumOfColumns = np.size(arr2D,1)
print("Number of Rows : ",NumOfRows)
print("Number of columns : ",NumOfColumns)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


Number of Rows :  3
Number of columns :  4


# Q4).

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Numpy array : ")
print(arr)
print("\n")


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print("2D Array")
print(arr_2d)

1D Numpy array : 
[0 1 2 3 4 5 6 7 8 9]


2D Array
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Q5).

In [5]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking : \n", np.vstack((a, b)))
print("\nHorizontal stacking : \n", np.hstack((a, b)))

Vertical stacking : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking : 
 [[1 2 5 6]
 [3 4 7 8]]


# Q6).

In [8]:
def unique(list1):
    x = np.array(list1)
    print(np.unique(x))
list1 = [11, 22, 33, 44, 44, 22]
print("The unique values from 1st list is : ")
unique(list1)
new_set = set(list1)
print("No of unique items in the list are : ", len(new_set))

The unique values from 1st list is : 
[11 22 33 44]
No of unique items in the list are :  4


# END